DECLARE @ERKEK AS FLOAT
DECLARE @KADIN AS FLOAT
DECLARE @TOPLAM AS FLOAT

SET @KADIN = (SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='K')
SET @ERKEK = (SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='E')
SET @TOPLAM = @KADIN / @ERKEK

SELECT @KADIN,@ERKEK,@TOPLAM

SELECT DISTINCT CITY,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='K' AND CITY = S.CITY) FEMALESALE,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='E' AND CITY = S.CITY) MALESALE,
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='K' AND CITY = S.CITY) /
(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='E' AND CITY = S.CITY) RATIO,
IIF((SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='K' AND CITY = S.CITY) /
	(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='E' AND CITY = S.CITY) > @TOPLAM, 'ORTALAMANIN ÜZERÝNDE','ORTALAMA ALTI') KADINORT
FROM LAB03 S
ORDER BY 1


