ALTER FUNCTION DBO.PLAYERINFO(@ID INT)
RETURNS TABLE 
AS
RETURN 
(
	SELECT P.PLAYER_NAME OYUNCU_ADI, DATEDIFF(YEAR, P.BIRTHDATE, GETDATE()) YAS,
	CASE
		WHEN DATEDIFF(YEAR, P.BIRTHDATE, GETDATE()) < 30 THEN '20-30 YAS ARASI'
		WHEN DATEDIFF(YEAR, P.BIRTHDATE, GETDATE()) BETWEEN 30 AND 40 THEN '30-40 YAS ARASI'
		WHEN DATEDIFF(YEAR, P.BIRTHDATE, GETDATE()) BETWEEN 40 AND 50 THEN '40-50 YAS ARASI'
		WHEN DATEDIFF(YEAR, P.BIRTHDATE, GETDATE()) BETWEEN 50 AND 60 THEN '50-60 YAS ARASI'

	END YAS_GRUBU,
	P.RATING PUAN, 
	(SELECT COUNT(ID) FROM LAB_MATCH_PLAYER WHERE PLAYERID=@ID)TOPLAM_MAC, 
	(SELECT COUNT(ID) FROM LAB_MATCH_PLAYER WHERE PLAYERTYPE = 'BACKUP' AND PLAYERID=@ID) YEDEK, 
	(SELECT COUNT(ID) FROM LAB_MATCH_PLAYER WHERE PLAYERTYPE = 'REAL' AND PLAYERID=@ID) ASIL, 
	(SELECT COUNT(DISTINCT TEAM) FROM LAB_MATCH_PLAYER WHERE PLAYERID=@ID) OYNANANTAKIMSAYISI, 
	(SELECT DATEDIFF(YEAR, MIN(DATE_), MAX(DATE_)) FROM LAB_MATCH_PLAYER WHERE PLAYERID=@ID)  TECRUBE
	FROM LAB_PLAYER P
	WHERE P.PLAYER_API_ID = @ID
)
GO

SELECT P.PLAYER_API_ID, INF.*
FROM LAB_PLAYER P
CROSS APPLY DBO.PLAYERINFO(P.PLAYER_API_ID) INF
ORDER BY INF.PUAN DESC