SELECT * FROM LAB01

SELECT * FROM LAB01
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >=40 AND DATEDIFF(YEAR,BIRTHDATE,GETDATE()) <=45 
AND GENDER = 'E'

SELECT * FROM LAB01
WHERE DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 40 AND 45 
AND GENDER = 'E'
