SELECT * FROM LAB06

SET LANGUAGE Turkish
SELECT DATEPART(YEAR,DATE_) YIL ,DATENAME(MONTH,DATE_) AY ,SUM(TOTALPRICE) TOPLAMSATIS
FROM LAB06
WHERE DATEPART(DAY,DATE_) BETWEEN 10 AND 15
GROUP BY DATEPART(YEAR,DATE_) ,DATENAME(MONTH,DATE_), DATEPART(MONTH,DATE_)
ORDER BY 1, DATEPART(MONTH,DATE_)
