SELECT * FROM LAB09

ALTER TABLE LAB09
ADD BIRTHDATE2 DATE

--KENDÝ YOLUM
UPDATE LAB09
SET BIRTHDATE2 = DATEFROMPARTS(RIGHT(BIRTHDATE,4),SUBSTRING(BIRTHDATE, 4,2),LEFT(BIRTHDATE,2))
WHERE NOT SUBSTRING(BIRTHDATE, 4,2) BETWEEN 13 AND 32

--2.BÝR YOL
UPDATE LAB09
SET BIRTHDATE2 = DATEFROMPARTS(RIGHT(BIRTHDATE,4),SUBSTRING(BIRTHDATE, 4,2),LEFT(BIRTHDATE,2))
WHERE  ISDATE(CONCAT_WS('-',RIGHT(BIRTHDATE,4),SUBSTRING(BIRTHDATE, 4,2),LEFT(BIRTHDATE,2))) = 1

SELECT *
FROM LAB09
WHERE SUBSTRING(BIRTHDATE, 4,2) BETWEEN 13 AND 32


SELECT BIRTHDATE,LEFT(BIRTHDATE,2) AS DAY_ FROM LAB09
SELECT BIRTHDATE,SUBSTRING(BIRTHDATE, 4,2) AS MONTH_ FROM LAB09
SELECT BIRTHDATE,RIGHT(BIRTHDATE,4) AS YEAR_ FROM LAB09

10.16.1958

