SELECT * FROM LAB04

SET LANGUAGE Turkish
SET DATEFIRST 1
SELECT DATEPART(WEEKDAY,DATE_) GUNSIRA,DATENAME(WEEKDAY,DATE_) GUN, SUM(TOTALPRICE) TOPLAMSATIS
FROM LAB04
GROUP BY DATENAME(WEEKDAY,DATE_),DATEPART(WEEKDAY,DATE_)
ORDER BY 1

--sIRALAMA KOLONUNU GÖSTERMEDEN SIRALAMA YAPMAK
SET LANGUAGE Turkish
SET DATEFIRST 1
SELECT DATENAME(WEEKDAY,DATE_) GUN, SUM(TOTALPRICE) TOPLAMSATIS
FROM LAB04
GROUP BY DATENAME(WEEKDAY,DATE_),DATEPART(WEEKDAY,DATE_)
ORDER BY DATEPART(WEEKDAY,DATE_) 


