DECLARE @RMODEL AS INT
DECLARE @RCITIES AS VARCHAR(2)
DECLARE @RANDOM AS INT
DECLARE @PLATES AS VARCHAR(100)
DECLARE @RLETTER AS VARCHAR(3)

SET @RMODEL = (SELECT TOP 1 ID  FROM LAB03_CARMODELS ORDER BY NEWID())
SET @RCITIES = (SELECT TOP 1 ID FROM LAB03_CITIES ORDER BY NEWID()) 
SET @RANDOM = 10 + RAND() * 989
SET @RLETTER = (SELECT TOP 1 LETTER FROM LAB03_LETTERS ORDER BY NEWID())



IF LEN(@RCITIES) < 2
	SET @RCITIES = CONCAT('0',@RCITIES)

DECLARE @I AS INT = 0
IF LEN(@RANDOM)< 3
BEGIN
	WHILE @I < 2
	BEGIN
		SET @RLETTER = @RLETTER + (SELECT TOP 1 LETTER FROM LAB03_LETTERS ORDER BY NEWID())
		SET @I = @I + 1
	END
	SET @PLATES = CONCAT(@RCITIES, @RLETTER , @RANDOM) 
END
ELSE
	WHILE @I < 1
	BEGIN
		SET @RLETTER = @RLETTER + (SELECT TOP 1 LETTER FROM LAB03_LETTERS ORDER BY NEWID())
		SET @I = @I + 1
	END
	SET @PLATES = CONCAT(@RCITIES, @RLETTER , @RANDOM)

INSERT INTO LAB03_PLATES(CARID,PLATE)
VALUES (@RMODEL,@PLATES)
GO 100


SELECT P.CARID,PLATE,M.TITLE,M.MODEL,M.BRAND,M.CASETYPE,M.FUEL,C.CITYNAME,M.YEAR_ 
FROM LAB03_PLATES P
JOIN LAB03_CARMODELS M ON M.ID=P.CARID 
JOIN LAB03_CITIES C ON C.ID = LEFT(P.PLATE,2)






