DECLARE @RCARID AS INT =1
DECLARE @RPLATE AS VARCHAR(10)
DECLARE @PTS AS TINYINT = 1
DECLARE @DATE AS DATETIME = '20240325 00:00:00:00'


DECLARE @I AS INT = 0
WHILE @I <= 240000
BEGIN
	DECLARE @DELAYED AS INT = RAND()*21
	SET @RCARID = (SELECT TOP 1 CARID FROM LAB04_PLATES ORDER BY NEWID())
	SET @RPLATE = (SELECT TOP 1 PLATE FROM LAB04_PLATES ORDER BY NEWID())
	SET @DATE = DATEADD(MILLISECOND,@DELAYED,@DATE)
	INSERT INTO LAB04_PTSLOG(PTSPOINTID,PLATE,DATE_)
	VALUES(@PTS,@RPLATE,@DATE)
	SET @I = @I + 1
END

SELECT P.PTSNAME,L.DATE_,L.PLATE,M.TITLE FROM LAB04_PTSLOG L
JOIN LAB04_PTSPOINT P ON P.ID=L.PTSPOINTID
JOIN LAB04_PLATES PL ON PL.PLATE= L.PLATE
JOIN LAB04_CARMODELS M ON M.ID=PL.CARID 
ORDER BY 2


TRUNCATE TABLE LAB04_PTSLOG