DECLARE @K AS INT = 0
WHILE @K<10000
BEGIN
	--TRUNCATE TABLE LAB05_SALES
	DECLARE @FICHENO AS VARCHAR(20) 
	DECLARE @DATE_  AS DATETIME 
	DECLARE @ITEMCODE AS VARCHAR(20) 
	DECLARE @ITEMNAME AS VARCHAR(100) 
	DECLARE @BRAND AS VARCHAR(100)
	DECLARE @CATEGORY1 AS VARCHAR(100)
	DECLARE @CATEGORY2 AS VARCHAR(100)
	DECLARE @CATEGORY3 AS VARCHAR(100)
	DECLARE @CATEGORY4 AS VARCHAR(100)
	DECLARE @AMOUNT AS INT 
	DECLARE @PRICE AS FLOAT 
	DECLARE @TOTALPRICE AS FLOAT 
	DECLARE @CUSTOMERCODE AS VARCHAR(100)
	DECLARE @CUSTOMERNAME AS VARCHAR(100)
	DECLARE @CUSTOMERBIRHTDATE AS DATE
	DECLARE @CUSTOMERGENDER CHAR(1)
	DECLARE @BRANCH AS VARCHAR(100) 
	DECLARE @CITY AS VARCHAR(100)
	DECLARE @DISTRICT AS VARCHAR(100)
	DECLARE @REGION AS VARCHAR(100)
	DECLARE @RANDID AS INT
	DECLARE @ITEMCOUNT AS INT

	SELECT @FICHENO = ISNULL(MAX(FICHENO),0) + 1 FROM LAB05_SALES 
	SET @FICHENO = REPLICATE('0', 10 - LEN(@FICHENO)) + @FICHENO

	SET @DATE_ = DATEADD(DAY, RAND()*365, '20230331')
	SET @DATE_ = DATEADD(HOUR, 8, @DATE_)
	SET @DATE_ = DATEADD(SECOND, RAND()*14*60*60, @DATE_)

	SET @ITEMCOUNT=1+(RAND()*9)

	SET @RANDID = RAND() * 10037
	SELECT @CITY=CITYNAME,@REGION=REGION FROM LAB05_CITIES WHERE @RANDID BETWEEN RANDOMBEG AND RANDOMEND

	SET @RANDID = (SELECT TOP 1 ID FROM LAB05_CUSTOMERS WHERE CITY=@CITY ORDER BY NEWID())
	SELECT @CUSTOMERCODE=ID,@CUSTOMERBIRHTDATE=BIRTHDATE,@CUSTOMERNAME=NAMESURNAME,@CUSTOMERGENDER=GENDER,@DISTRICT=TOWN
	FROM LAB05_CUSTOMERS
	WHERE ID = @RANDID

	SET @BRANCH=@CITY

	DECLARE @I AS INT=0
	WHILE @I<@ITEMCOUNT
	BEGIN
		SET @RANDID = (SELECT TOP 1 ID FROM LAB05_ITEMS ORDER BY NEWID())
		SELECT @ITEMCODE=ITEMCODE, @ITEMNAME=ITEMNAME, @BRAND=BRAND, @CATEGORY1=CATEGORY1, @CATEGORY2=CATEGORY2, @CATEGORY3=CATEGORY3, @CATEGORY4=CATEGORY4, @PRICE=SALEPRICE
		FROM LAB05_ITEMS
		WHERE ID=@RANDID

		SET @AMOUNT = 1 + (RAND()*9)
		SET @TOTALPRICE=@AMOUNT * @PRICE
		--SELECT @FICHENO,@DATE_,@FICHENO, @DATE_, @ITEMCODE, @ITEMNAME, @BRAND, @CATEGORY1, @CATEGORY2, @CATEGORY3, @CATEGORY4,@RANDID,@CITY,@CUSTOMERNAME


		INSERT INTO LAB05_SALES(
		FICHENO, DATE_, ITEMCODE, ITEMNAME, BRAND, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, AMOUNT, PRICE, TOTALPRICE,
		CUSTOMERCODE, CUSTOMERNAME, CUSTOMERBIRHTDATE, CUSTOMERGENDER, BRANCH, CITY, DISTRICT, REGION)
		VALUES (
		@FICHENO, @DATE_, @ITEMCODE, @ITEMNAME, @BRAND, @CATEGORY1, @CATEGORY2, @CATEGORY3, @CATEGORY4, @AMOUNT, @PRICE, @TOTALPRICE,
		@CUSTOMERCODE, @CUSTOMERNAME, @CUSTOMERBIRHTDATE, @CUSTOMERGENDER, @BRANCH, @CITY, @DISTRICT, @REGION)
	SET @I=@I+1
	END
SET @K=@K+1
END