SELECT MAX(DATE_),MIN(DATE_) FROM LAB_SALES
ORDER BY DATE_

ALTER PROC CATEGORYSALES
@BEGDATE AS DATE = '2019-01-01',
@ENDATE AS DATE = '2019-12-31',
@CITIES AS VARCHAR(400)
AS

SELECT CONCAT_WS(' ', 'BASLANGIÇ TARÝHÝ=:'+CONCAT_WS('.', DAY(@BEGDATE),MONTH(@BEGDATE),YEAR(@BEGDATE)), 
'BÝTÝÞ TARÝHÝ=:'+CONCAT_WS('.',DAY(@ENDATE), MONTH(@ENDATE), YEAR(@ENDATE)),
'ÞEHÝRLER=:'+UPPER(@CITIES)) AS FILTER

-- TARÝH GÖSTERÝMÝNDE KISA YOL
	/*SELECT CONCAT_WS(' ', 'BASLANGIÇ TARÝHÝ=:'+CONVERT(VARCHAR, @BEGDATE, 104), 
	'BÝTÝÞ TARÝHÝ=:'+CONVERT(VARCHAR, @ENDATE, 104),
	'ÞEHÝRLER=:'+UPPER(@CITIES)) AS FILTER
	*/

SELECT CATEGORY1, SUM(TOTALPRICE) as TOTALSALE FROM LAB_SALES
WHERE DATE_ BETWEEN @BEGDATE AND @ENDATE AND CITY IN (SELECT VALUE FROM string_split(@CITIES, ','))
GROUP BY CATEGORY1

EXEC CATEGORYSALES '20190401', '20190430', 'ÝSTANBUL,ÝZMÝR,BURSA'

-- Print ile yazdýrma
print 'EMÝRHAN'+char(ASCII('
'))+ 'polat'