-- MARKA, TRAFÝÐE ÇIKIÞ TARÝHÝ BAÞLANGIÇ BÝTÝÞ
SELECT * FROM LAB_PLATES

ALTER PROC LICENCEDATE
@BRAND AS VARCHAR(50) = '%',
@BEGDATE AS DATE,
@ENDATE AS DATE
AS
SELECT * FROM LAB_PLATES
WHERE BRAND LIKE @BRAND AND LICENCEDATE BETWEEN @BEGDATE AND @ENDATE
ORDER BY LICENCEDATE

EXEC LICENCEDATE @BEGDATE = '20150101', @ENDATE = '20200101', @BRAND = 'Mercedes'
