DECLARE @A AS INT
SELECT @A=COUNT(*) FROM LAB03_CUSTOMERS

DECLARE @B AS INT
SELECT @B=COUNT(*) FROM LAB03_ITEMS


DECLARE @AMOUNT AS INT
SET @AMOUNT= 1+RAND()*19

DECLARE @RANDOMCUSTOMER AS INT
SET @RANDOMCUSTOMER = RAND() * @A

DECLARE @RANDOMITEM AS INT
SET @RANDOMITEM = RAND() * @B

DECLARE @UNITPRICE AS FLOAT
SELECT @UNITPRICE=UNITPRICE FROM LAB03_ITEMS
WHERE ID = @RANDOMITEM

DECLARE @LINETOTAL AS FLOAT
SET @LINETOTAL= @AMOUNT * @UNITPRICE

DECLARE @DATE AS DATETIME
DECLARE @RAND AS INT
SET @RAND=RAND()*365
SET @DATE=DATEADD(DAY,@RAND,'2021-01-01')
SET @DATE=DATEADD(HOUR,8,@DATE)
SET @RAND = RAND()*12*60*60
SET @DATE=DATEADD(SECOND,@RAND,@DATE)

INSERT INTO LAB03_SALES(CUSTOMERID,DATE_,AMOUNT,UNITPRICE,LINETOTAL)
VALUES(@RANDOMCUSTOMER,'2019-01-01',@AMOUNT,@UNITPRICE,@LINETOTAL)

SELECT * FROM LAB03_SALES S
JOIN LAB03_CUSTOMERS C ON C.ID=S.CUSTOMERID


