SELECT * FROM LAB_USER
SELECT * FROM LAB_USERLOGIN_LOG

TRUNCATE  TABLE LAB_USERLOGIN_LOG

ALTER PROC LOG_ISLEM
@USERNAME AS VARCHAR(100),
@PASSWORD AS VARCHAR(100)
AS
IF @USERNAME IN (SELECT USERNAME_ FROM LAB_USER)
	BEGIN
		IF @PASSWORD = (SELECT PASSWORD_ FROM LAB_USER WHERE USERNAME_= @USERNAME)
			BEGIN
				INSERT INTO LAB_USERLOGIN_LOG
				SELECT ID, USERNAME_, 'SUCCESS', EMAIL, GETDATE() FROM LAB_USER WHERE USERNAME_=@USERNAME
			END
		ELSE
		BEGIN
			INSERT INTO LAB_USERLOGIN_LOG
			SELECT ID, USERNAME_, 'FAILURE', EMAIL, GETDATE() FROM LAB_USER WHERE USERNAME_= @USERNAME
			SELECT 'KULLANICI ADI VEYA PAROLA HATALI!'
		END
	END
ELSE SELECT 'BÖYLE BÝR KULLANICI BULUNAMADI'

EXEC LOG_ISLEM 'N_OZSDIMITCI', '4598DD75'
