-- ÞEHÝRDE KÝÞÝ BAÞI ARAÇ SAYISI, MARKA, TRAFÝÐE ÇIKIÞ TARÝHÝ PARAMETRELERÝ

SELECT * FROM LAB_PLATES
SELECT * FROM LAB_CITIES

ALTER PROC KISIBASI
@BRAND AS VARCHAR(50) = '%',
@BEGDATE AS DATE,
@ENDATE AS DATE,
@REGION AS VARCHAR(200)
AS
SELECT C.ID,C.CITYNAME AS SEHIR, C.POPULATION AS NUFUS, C.REGION BOLGE,
--P.BRAND MARKA, 
COUNT(P.PLATE) ARACSAYISI, ROUND(COUNT(P.PLATE)/CONVERT(FLOAT,C.POPULATION),3) AS KISIBASI_ARAC  
FROM LAB_CITIES C, LAB_PLATES P
WHERE C.ID = P.CITYNR AND P.BRAND LIKE @BRAND AND P.LICENCEDATE BETWEEN @BEGDATE AND @ENDATE AND 
C.REGION IN (SELECT VALUE FROM string_split(@REGION,','))
GROUP BY C.CITYNAME, C.POPULATION , C.REGION, C.ID --P.BRAND
ORDER BY 1

SELECT C.ID,C.CITYNAME AS SEHIR, C.POPULATION AS NUFUS, C.REGION BOLGE,
P.BRAND MARKA, 
COUNT(P.PLATE) ARACSAYISI, ROUND(COUNT(P.PLATE)/CONVERT(FLOAT,C.POPULATION),3) AS KISIBASI_ARAC  
FROM LAB_CITIES C, LAB_PLATES P
WHERE C.ID = P.CITYNR AND P.BRAND LIKE @BRAND AND P.LICENCEDATE BETWEEN @BEGDATE AND @ENDATE AND 
C.REGION IN (SELECT VALUE FROM string_split(@REGION,','))
GROUP BY C.CITYNAME, C.POPULATION , C.REGION, C.ID, P.BRAND
ORDER BY C.ID, P.BRAND

EXEC KISIBASI @BEGDATE = '20000101', @ENDATE = '20221231', @REGION = 'Karadeniz,Akdeniz,Marmara'

SELECT ROUND(CONVERT(FLOAT, 143001 / 2263373),4)