DECLARE @RANDID AS INT
SELECT TOP 1 @RANDID=ID FROM LAB04_CUSTOMERS ORDER BY NEWID() 
--SET @RANDID = 1 + RAND() *  (SELECT (COUNT(*)-1) FROM LAB04_CUSTOMERS)


DECLARE @CUSTOMERID AS INT
DECLARE @CUSTOMERNAME AS VARCHAR(100)
DECLARE @GIFTCOST AS FLOAT

SELECT @CUSTOMERID=CUSTOMERID, @CUSTOMERNAME=CUSTOMERNAME, @GIFTCOST=(SUM(TOTALPRICE)/2) FROM LAB04_SALES S
JOIN LAB04_CUSTOMERS C ON C.ID=S.CUSTOMERID
WHERE C.ID= @RANDID AND C.ID  NOT IN (SELECT CUSTOMERID FROM RAFFLE)
GROUP BY CUSTOMERID,CUSTOMERNAME

--CREATE TABLE RAFFLE(
--CUSTOMERID INT, CUSTOMERNAME VARCHAR(100), GIFTCOST FLOAT)

INSERT INTO RAFFLE(CUSTOMERID,CUSTOMERNAME,GIFTCOST)
VALUES(@CUSTOMERID,@CUSTOMERNAME,@GIFTCOST)

SELECT * FROM RAFFLE


