--RAND -> 0 ÝLE 1 ARASINDA RASTGELE DEÐERLER ÜRETÝR. PARAMETRE ALMAZ
SELECT RAND()

--1 ÝLE 100 ARASI DEÐER
SELECT RAND() * 100
SELECT CONVERT(INT,RAND()*100)

-- 50 ÝLE 100 ARASINDA DEÐER ÜRET
SELECT 50 + CONVERT(INT,RAND()*50)