DECLARE @ID AS INT
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @BIRTHDATE AS DATE

DECLARE CRS CURSOR FOR --FORDAN SONRA HANGÝ TABLO ÜZERÝNDE DÖNECEÐÝMÝZÝ TANIMLARIZ
	SELECT ID,NAMESURNAME,BIRTHDATE FROM CUSTOMERS
	WHERE CITY='ANKARA' AND TOWN='ÇANKAYA'
OPEN CRS
	FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@BIRTHDATE -- DÖNGÜDEKÝ ÝLK ELEMANI ALMAK ÝÇÝN
	WHILE @@FETCH_STATUS = 0 --SON ELEMANA GELÝP GELMEDÝÐÝNÝ KONTROL EDER (0 SA GELMEDÝ)
		BEGIN -- BU BEGIN END ÝÇÝNE DÖNGÜNÜN YAPMASI ÝSTENEN EYLEMLER YAZILIR
			PRINT @NAMESURNAME
			FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@BIRTHDATE -- SON ELEMANA GELÝNMEDÝYSE HANGÝ ÝÞLEMÝ YAPARAK DEVAM EDECEÐÝNE BAKAR
		END
CLOSE CRS
DEALLOCATE CRS