DECLARE @ID AS INT
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @GENDER AS CHAR(1)
DECLARE @BIRTHDATE AS DATE 
DECLARE @EMAIL AS VARCHAR(100)
DECLARE @AGE AS INT
DECLARE @MSG AS VARCHAR(1000)

DECLARE CRS CURSOR FOR
	SELECT 
	ID,NAMESURNAME,GENDER,BIRTHDATE,'sqlcalis14@gmail.com' as EMAIL,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE
	FROM USERS
	WHERE DATEPART(DAY,BIRTHDATE)=DATEPART(DAY,GETDATE())
	AND DATEPART(MONTH,BIRTHDATE)=DATEPART(MONTH,GETDATE())
OPEN CRS
	FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@GENDER,@BIRTHDATE,@EMAIL,@AGE
	WHILE @@FETCH_STATUS=0
		BEGIN
			SET @MSG = CONCAT_WS(' ','Sayýn', @NAMESURNAME, IIF(@GENDER='K','Haným;','Bey;') + CHAR(13) + CONVERT(VARCHAR,@AGE) + '.', 'yaþýnýzý kutlar, saðlýklý ömürler dileriz')
			PRINT @MSG
			EXEC msdb.dbo.sp_send_dbmail
				    @profile_name = 'SQLMAIL',
					@recipients = @EMAIL,
					@body = @MSG,
					@subject = 'Doðum Gününüz Kutlu Olsun!';
			FETCH NEXT FROM CRS INTO @ID,@NAMESURNAME,@GENDER,@BIRTHDATE,@EMAIL,@AGE
		END
CLOSE CRS
DEALLOCATE CRS
