SELECT BRAND,
CASE
	WHEN DATEDIFF(YEAR,YEAR_,LICENCEDATE) = 0 THEN 'AYNI YIL TRAFÝÐE ÇIKMIÞ'
	WHEN DATEDIFF(YEAR,YEAR_,LICENCEDATE) = 1 THEN 'BÝR YIL SONRA TRAFÝÐE ÇIKMIÞ'
	WHEN DATEDIFF(YEAR,YEAR_,LICENCEDATE) = 2 THEN 'ÝKÝ YIL SONRA TRAFÝÐE ÇIKMIÞ'
END AS STATUS_
,COUNT(*) COUNT_
FROM LAB02 
GROUP BY BRAND,DATEDIFF(YEAR,YEAR_,LICENCEDATE)
ORDER BY 1 ,2
