--SELECT * FROM LAB03

SELECT CONCAT_WS('-',CATEGORY1CODE, REPLICATE('0',(6 - LEN(ITEMCODE))) + ITEMCODE, 
CONVERT(VARCHAR, CONVERT(DATE,GETDATE()),121) 
, REPLACE(CONVERT(VARCHAR, GETDATE(),108), ':','-') )
FROM LAB03

SELECT CONVERT(VARCHAR, CONVERT(DATE, GETDATE()), 121) 
FROM LAB03





