CREATE VIEW VWBUGUNDOGANLAR
AS
SELECT *, CONCAT_WS(' ','Sayýn',ADSOYAD,IIF(CINSIYET='K','Haným','Bey')+';',CONVERT(VARCHAR,YAS)+'.','yaþýnýzý kutlar, aileniz ve sevdklerinizle mutluluklar dileriz') MESAJ
FROM
(
SELECT NAMESURNAME ADSOYAD,GENDER CINSIYET,BIRTHDATE DOGUMTARIHI,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) YAS
FROM USERS
WHERE DATEPART(MONTH,BIRTHDATE)=DATEPART(MONTH,GETDATE()) AND
DATEPART(DAY,BIRTHDATE)=DATEPART(DAY,GETDATE())
) DYNAMICVW

SELECT * FROM VWBUGUNDOGANLAR
