--ALIÞTIRMA 2
CREATE VIEW VWINVOICEDURATION
AS
SELECT CT.CITY SEHIR, AVG(DATEDIFF(HOUR,O.DATE_, I.DATE_)) ORT_HAZIRLIK_SURESI
FROM INVOICES I
JOIN ORDERS O ON O.ID=I.ORDERID
JOIN ADDRESS A ON A.ID=I.ADDRESSID
JOIN CITIES CT ON CT.ID= A.CITYID
GROUP BY CT.CITY

SELECT * FROM VWINVOICEDURATION
