--ALIÞTIRMA1
ALTER VIEW VWMONTHLYSALES
AS
SELECT DATEPART(MONTH,DATE_) DATENR,DATENAME(MONTH,DATE_) MONTHNAME_,SUM(TOTALPRICE) TOTALSALE
FROM ORDERS 
GROUP BY DATENAME(MONTH,DATE_),DATEPART(MONTH,DATE_)


SET LANGUAGE turkish
SELECT MONTHNAME_,TOTALSALE FROM VWMONTHLYSALES
ORDER BY DATENR


