SELECT * FROM LAB01

SELECT CONVERT(DATE,DATE_) AS TARIH ,CONVERT(TIME,DATE_) AS SAAT FROM LAB01

ALTER TABLE LAB01
ADD  TARIH DATE, SAAT TIME

UPDATE LAB01
SET TARIH=CONVERT(DATE,DATE_),
SAAT = CONVERT(TIME,DATE_)