ALTER TABLE #RESULT
(ID INT, ITEMCODE VARCHAR(100), ITEMNAME VARCHAR(100), TOTALSALE_M FLOAT, TOTALSALE_F FLOAT, RATIO FLOAT)

SELECT * FROM #RESULT

INSERT INTO #RESULT (ID,ITEMCODE,ITEMNAME)
SELECT ID,ITEMCODE,ITEMNAME FROM ITEMS

UPDATE #RESULT SET TOTALSALE_M=
(SELECT SUM(OD.LINETOTAL) TOTALSALE
FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
WHERE ITEMID = #RESULT.ID
AND U.GENDER='E')

UPDATE #RESULT SET TOTALSALE_F=
(SELECT SUM(OD.LINETOTAL) TOTALSALE
FROM ORDERDETAILS OD
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN USERS U ON U.ID=O.USERID
WHERE ITEMID = #RESULT.ID
AND U.GENDER='K')

UPDATE #RESULT SET RATIO=TOTALSALE_M/TOTALSALE_F