SELECT * FROM LAB05

SELECT CUSTOMERNAME MUSTERIADI,DATEDIFF(YEAR,CUSTOMERBIRHTDATE, GETDATE()) MUSTERIYAS,
DATEPART(HOUR,DATE_) SAAT, MAX(TOTALPRICE) ENYUKSEKALISVERIS
FROM LAB05
WHERE CUSTOMERGENDER='K' AND  DATEDIFF(YEAR,CUSTOMERBIRHTDATE, GETDATE()) BETWEEN 30 AND 50
GROUP BY CUSTOMERNAME,DATEDIFF(YEAR,CUSTOMERBIRHTDATE, GETDATE()),DATEPART(HOUR,DATE_)
ORDER BY MAX(TOTALPRICE) DESC

