SELECT CITY
FROM LAB08
WHERE MONTH(DATEADD(MONTH,-1,GETDATE())) = MONTH(DATE_) 
GROUP BY CITY


SET LANGUAGE Turkish
SELECT CITY,SUM(TOTALPRICE) AS TOTALSALE,

(	
	SELECT SUM(TOTALPRICE) FROM LAB08
	WHERE MONTH(DATEADD(MONTH,-1,GETDATE())) = MONTH(DATE_) AND CITY=L.CITY
	GROUP BY CITY
) AS TOTALSALEPREVMONTH
FROM LAB08 L
WHERE MONTH(GETDATE()) = MONTH(DATE_) OR  MONTH(DATEADD(MONTH,-1,GETDATE())) = MONTH(DATE_) 
GROUP BY  CITY,DATE_
ORDER BY 1


