SELECT * 
FROM LAB07



SELECT NAMESURNAME,BIRTHDATE
FROM LAB07
WHERE DAY(BIRTHDATE) = DAY(GETDATE()) AND MONTH(BIRTHDATE) = MONTH(GETDATE())
ORDER BY 1


SELECT DATEDIFF(MONTH, '2019-01-29', GETDATE())